"""Remove StudentStatus and add inactivation fields

Revision ID: 0e0599c655c3
Revises: bcf99c2b98d0
Create Date: 2026-02-24 10:08:11.300167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e0599c655c3'
down_revision = 'bcf99c2b98d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inactivated_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('inactivate_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('inactivated_by', sa.Integer(), nullable=True))
        batch_op.drop_column('StudentStatus')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StudentStatus', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('inactivated_by')
        batch_op.drop_column('inactivate_reason')
        batch_op.drop_column('inactivated_date')

    # ### end Alembic commands ###
