"""parameter table

Revision ID: 48726e71f5ef
Revises: 666eff6fd62b
Create Date: 2026-06-13 12:38:41.525403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48726e71f5ef'
down_revision = '666eff6fd62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_value', sa.String(length=255), nullable=False),
    sa.Column('parameter_type', sa.String(length=255), nullable=False),
    sa.Column('parameter_description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_table')
    # ### end Alembic commands ###
