"""add remittance models and sequence fields

Revision ID: 9642ede2d1a6
Revises: 48726e71f5ef
Create Date: 2026-08-04 16:09:02.539151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9642ede2d1a6'
down_revision = '48726e71f5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance_master',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_no', sa.String(length=50), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('cash_in_hand', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected'), server_default='Pending', nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remittance_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remittance_master_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remittance_master_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_remittance_master_remittance_no'), ['remittance_no'], unique=True)

    op.create_table('remittance_denominations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_id', sa.BigInteger(), nullable=False),
    sa.Column('denomination', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remittance_denominations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remittance_denominations_remittance_id'), ['remittance_id'], unique=False)

    op.create_table('remittance_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remittance_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_receipt_id', sa.Integer(), nullable=False),
    sa.Column('receipt_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['fee_receipt_id'], ['fee_payments.payment_id'], ),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittance_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remittance_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remittance_receipts_fee_receipt_id'), ['fee_receipt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_remittance_receipts_remittance_id'), ['remittance_id'], unique=False)

    with op.batch_alter_table('enrollment_sequences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remittance_prefix', sa.String(length=20), server_default='REM', nullable=False))
        batch_op.add_column(sa.Column('last_remittance_no', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_sequences', schema=None) as batch_op:
        batch_op.drop_column('last_remittance_no')
        batch_op.drop_column('remittance_prefix')

    with op.batch_alter_table('remittance_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remittance_receipts_remittance_id'))
        batch_op.drop_index(batch_op.f('ix_remittance_receipts_fee_receipt_id'))

    op.drop_table('remittance_receipts')
    with op.batch_alter_table('remittance_denominations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remittance_denominations_remittance_id'))

    op.drop_table('remittance_denominations')
    with op.batch_alter_table('remittance_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remittance_master_remittance_no'))
        batch_op.drop_index(batch_op.f('ix_remittance_master_business_date'))
        batch_op.drop_index(batch_op.f('ix_remittance_master_branch_id'))

    op.drop_table('remittance_master')
    # ### end Alembic commands ###
